figure('Name','Simulation Plot Window','NumberTitle','off');
[x,y] = meshgrid(1:15,1:15);
tri = delaunay(x,y);
z = peaks(15);
trisurf(tri,x,y,z);
axis off;
axis equal;
%shading interp;
f=getframe(gcf);
imwrite(f.cdata,'1.jpg');
